# Generated by Django 3.2.9 on 2021-12-03 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("positions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="code",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
